commonLabels:
  app: semsearch-clip-milvus
resources:
- semsearch-api-deployment.yaml
- semsearch-api-hpa.yaml
- semsearch-api-service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: gcr.io/fsdl2022/semsearch-clip-milvus-k8s
  newTag: latest
