apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: semsearch-serverclip-milvus
  name: semsearch-clip-milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semsearch-clip-milvus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: semsearch-clip-milvus
    spec:
      containers:
        - args:
            - bash
            - -c
            - make run-service-development
          image: gcr.io/fsdl2022/semsearch-clip-milvus-k8s:latest
          name: semsearch-clip-milvus-k8s
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
